inherit_from: .rubocop_todo.yml

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
